amount=int(input())
five_hundred_notes=amount//500
remaining_balance=amount%500
print("five_hundred_notes(500):",five_hundred_notes)
one_hundred_notes=remaining_balance//100
remaining_amount=remaining_balance%100
print("one_hundred_notes(100):",one_hundred_notes)
fifty_notes=remaining_amount//50
remaining_notes=remaining_amount%50
print("fifty_notes(50):",fifty_notes)
ten_notes=remaining_notes//10
remaining_notes=remaining_notes%10
print("ten_notes(50):",ten_notes)
